import { t } from "../i18n.mjs";

export const HABITAT_COPY = {
  en: {
    "observe.title": "The living habitat",
    "observe.eyebrow": "IMMORTAL / OBSERVATORY",
    "observe.subtitle": "A little world. Every life, its own character.",
    "observe.local": "Local simulation",
    "observe.saved": "Saved in this browser",
    "observe.storage": "About this habitat",
    "observe.storageNote":
      "Movement, feeding and energy stay in this browser. The scene pauses when hidden or closed; it does not catch up offline. Clearing site data removes this progress, not the on-chain identity. The activity list covers this visit only; it is not a verified life archive.",
    "observe.all": "All flies",
    "observe.mine": "Mine",
    "observe.count": "{n} in view",
    "observe.select": "Choose a fly",
    "observe.search": "Find a name or #id",
    "observe.searchToggle": "Find a fly",
    "observe.noMatch": "No matching fly. Try a name or number.",
    "observe.watch": "Observe",
    "observe.food": "Scatter food",
    "observe.gust": "Gust",
    "observe.hint.move":
      "Select a fly to meet it. Drag the ground to look around.",
    "observe.hint.feed":
      "Tap the ground to leave food. Hungry flies eat when they reach it.",
    "observe.hint.gust":
      "Tap the ground to send a brief gust through the habitat.",
    "observe.fit": "Fit view",
    "observe.zoomIn": "Zoom in",
    "observe.zoomOut": "Zoom out",
    "observe.pause": "Pause",
    "observe.resume": "Resume",
    "observe.paused": "Paused",
    "observe.controls": "View controls",
    "observe.current": "CURRENT OBSERVATION",
    "observe.yours": "You own this fly",
    "observe.public": "Public observation",
    "observe.owner": "Owner",
    "observe.details": "Details",
    "observe.collapse": "Collapse",
    "observe.feed": "Feed this fly",
    "observe.focus": "Locate",
    "observe.energy": "Local energy",
    "observe.activity.fly": "In flight",
    "observe.activity.rest": "Resting",
    "observe.activity.held": "Being moved",
    "observe.events": "This visit",
    "observe.eventsEmpty":
      "Try feeding a fly. Its local response will appear here.",
    "observe.event.feed": "Fed #{id} · energy +{amount}",
    "observe.event.ate": "#{id} found food · energy +{amount}",
    "observe.event.food": "Food placed on the ground",
    "observe.event.gust": "A local gust crossed the habitat",
    "observe.event.journal": "Recorded stimulus applied locally to #{id}",
    "observe.event.move": "Moved #{id} in this browser",
    "observe.guest": "Meet your own fly",
    "observe.guestNote":
      "Anyone can observe and try local feeding. Connect your wallet to find and manage your own fly.",
    "observe.connect": "Connect to find mine",
    "observe.connectError": "Could not connect. Please try again.",
    "observe.noMine": "No flies in this wallet",
    "observe.noMineNote":
      "You can hatch your first Soul or return to the public habitat.",
    "observe.backAll": "Observe all flies",
    "observe.empty": "The habitat is waiting",
    "observe.emptyNote":
      "Hatched flies will appear here. Connect a wallet to hatch your first Soul.",
    "observe.loading": "Opening the habitat…",
    "observe.loadingNote": "Reading the collection and its inhabitants.",
    "observe.error": "The habitat could not be loaded",
    "observe.errorNote":
      "The collection could not be read. Try again in a moment.",
    "observe.keyboard":
      "Keyboard: arrows move the view, + / − zoom, Space pauses, Enter places the selected stimulus at the centre. Shift + arrows moves a fly you own. Escape returns to observation.",
    "observe.walletLead":
      "Choose a wallet to find your flies. Connecting does not send a transaction.",
    "observe.retry": "Try again",
    "observe.manage": "Manage this Soul",
    "observe.manageNote":
      "Naming and transfers change the on-chain Soul and require a wallet transaction.",
    "observe.hatchTitle": "Hatch your first Soul",
    "observe.hatchNote":
      "BNB Smart Chain · gas only · one Gen0 hatch per wallet. Hatching needs two wallet confirmations.",
    "observe.market": "Visit the market",
    "observe.more": "Explore",
    "observe.full": "Energy is already full",
    "observe.resumeHint": "The scene is paused. Resume to watch the response.",
  },
  zh: {
    "observe.title": "活体观察台",
    "observe.eyebrow": "IMMORTAL / 栖息地",
    "observe.subtitle": "一方小世界，每只生命各有模样。",
    "observe.local": "本地模拟",
    "observe.saved": "保存在本浏览器",
    "observe.storage": "关于这个栖息地",
    "observe.storageNote":
      "飞行、投食与体力保存在当前浏览器。隐藏或关闭页面后暂停，不补算离线时间。清除网站数据会丢失这里的进度，链上身份不受影响。下方动态仅记录本次访问，不是已验证的生命档案。",
    "observe.all": "全部",
    "observe.mine": "我的",
    "observe.count": "当前 {n} 只",
    "observe.select": "选择一只果蝇",
    "observe.search": "搜索名字或 #编号",
    "observe.searchToggle": "查找果蝇",
    "observe.noMatch": "没有找到。试试名字或编号。",
    "observe.watch": "观察",
    "observe.food": "地面投食",
    "observe.gust": "阵风",
    "observe.hint.move": "点一只，看看它。拖动空地移动视野。",
    "observe.hint.feed": "点击地面放下食物，饥饿的果蝇靠近后会进食。",
    "observe.hint.gust": "点击地面，送入一阵短暂的风。",
    "observe.fit": "适应视野",
    "observe.zoomIn": "放大视野",
    "observe.zoomOut": "缩小视野",
    "observe.pause": "暂停",
    "observe.resume": "继续",
    "observe.paused": "已暂停",
    "observe.controls": "视野控制",
    "observe.current": "正在观察",
    "observe.yours": "你持有这只",
    "observe.public": "公共观察",
    "observe.owner": "持有者",
    "observe.details": "展开详情",
    "observe.collapse": "收起详情",
    "observe.feed": "喂这只",
    "observe.focus": "定位",
    "observe.energy": "本地体力",
    "observe.activity.fly": "飞行中",
    "observe.activity.rest": "休息中",
    "observe.activity.held": "正在搬动",
    "observe.events": "本次动态",
    "observe.eventsEmpty": "试着喂一只果蝇，这里会记录它的本地反应。",
    "observe.event.feed": "喂了 #{id} · 体力 +{amount}",
    "observe.event.ate": "#{id} 找到食物 · 体力 +{amount}",
    "observe.event.food": "已在地面放下食物",
    "observe.event.gust": "一阵风经过本地栖息地",
    "observe.event.journal": "已为 #{id} 在本地应用已记录的刺激",
    "observe.event.move": "已在本浏览器搬动 #{id}",
    "observe.guest": "遇见属于你的那只",
    "observe.guestNote":
      "访客也能观察和体验本地喂食。连接钱包，找到并管理你的果蝇。",
    "observe.connect": "连接钱包，找到我的",
    "observe.connectError": "连接未完成，请重试。",
    "observe.noMine": "这个钱包还没有果蝇",
    "observe.noMineNote": "可以孵化你的第一只灵魂，或回到公共栖息地继续观察。",
    "observe.backAll": "观察全部果蝇",
    "observe.empty": "栖息地静候生命",
    "observe.emptyNote":
      "已孵化的果蝇会出现在这里。连接钱包，孵化你的第一只灵魂。",
    "observe.loading": "正在打开栖息地…",
    "observe.loadingNote": "读取集合与已经出生的生命。",
    "observe.error": "暂时无法读取栖息地",
    "observe.errorNote": "集合读取失败，请稍后重试。",
    "observe.keyboard":
      "键盘：方向键移动视野，+ / − 缩放，空格暂停，Enter 在视野中心施加所选刺激。Shift + 方向键可搬动你持有的果蝇，Esc 返回观察。",
    "observe.walletLead": "选择钱包，找到你的果蝇。连接本身不会发起交易。",
    "observe.retry": "重新读取",
    "observe.manage": "管理这只灵魂",
    "observe.manageNote": "改名和转移会更改链上灵魂，需要确认钱包交易。",
    "observe.hatchTitle": "孵化你的第一只灵魂",
    "observe.hatchNote":
      "BNB Smart Chain · 只付 gas · 每个钱包终身一次 Gen0 孵化。需要两次钱包确认。",
    "observe.market": "前往市场",
    "observe.more": "探索更多",
    "observe.full": "体力已经满了",
    "observe.resumeHint": "场景已暂停，继续后可观察反应。",
  },
};

export function habitatText(locale, key, vars = {}) {
  let text = HABITAT_COPY[locale]?.[key] ?? HABITAT_COPY.en[key];
  if (text === undefined) return t(locale, key, vars);
  for (const [name, value] of Object.entries(vars))
    text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
